name: Build LaTeX files

on:
  push:
    paths:
      - '**.tex'
      - '**.sty'
      - '**img**'
      - '**dummy**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile hio/editorial.tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: editorial.tex
          working_directory: hio

      - name: Push new pdf-s
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add hio/editorial.pdf
          git commit -m "Update pdf"
          git push
