name: Build LaTeX files

on:
  push:
    paths:
      - '**.tex'
      - '**.sty'
      - '**img**'
      - '**dummy**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile pripreme/dan1/zadaci.tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: zadaci.tex
          working_directory: pripreme/dan1

      - name: Compile pripreme/dan2/zadaci.tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: zadaci.tex
          working_directory: pripreme/dan2

      - name: Push new pdf-s
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add pripreme/dan1/zadaci.pdf pripreme/dan2/zadaci.pdf
          git commit -m "Update pdf"
          git push
